django_app/configure/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls')),
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

django_app/post/urls.py
from django.conf.urls import url

from . import views

app_name = 'post'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<post_pk>\d+)/delete$', views.post_delete, name='post_delete'),
    url(r'^(?P<post_pk>\d+)/modify$', views.post_modify, name='post_modify'),

]

django_app/member/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

django_app/post/models.py
from django.db import models
from django.conf import settings

'''
Post모델
author(User 모델로 연결)
photo
comment
created_date
modify_date
'''


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.ImageField(blank=True)
    comment = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now_add=True)

django_app/post/forms.py
from django import forms


class PostForm(forms.Form):
    photo = forms.ImageField(
        label='image',
        widget=forms.FileInput(),
    )
    comment = forms.CharField(
        label='comment',
        widget=forms.TextInput(),
    )

django_app/member/views.py
from django.shortcuts import render

# Create your views here.

django_app/post/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm
from .models import Post


def post_list(request):
    posts = Post.objects.all()

    context = {
        'posts': posts
    }

    return render(request, 'post/post_list.html', context)


def post_delete(request, post_pk):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_pk)
        post.delete()
    return redirect('post:post_list')


def post_modify(request, post_pk):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_pk)
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            image = request.FILES['photo']
            comment = request.POST['comment']
            post.photo = image
            post.comment = comment
            post.save()

        return redirect('post:post_list')

    else:
        form = PostForm()

    context = {
        'form': form
    }
    return render(request, 'post/post_modify.html', context)

django_app/templates/common/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

django_app/templates/post/post_list.html
{% extends 'common/base.html' %}

{% block content %}
    {% for post in posts %}
        <div>{{ post.pk }}</div>
        <div>{{ post.author }}</div>
        <div style="width: 50%; height: auto;"><img src="{{ post.photo.url }}" alt=""></div>
        <div>{{ post.comment }}</div>
        <div>{{ post.created_date }}</div>
        <form action="{% url 'post:post_delete' post_pk=post.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit">삭제하기</button>
        </form>
        <div>---------------------------------------</div>
        <br>

    {% endfor %}


{% endblock %}

django_app/templates/post/post_modify.html
{% extends 'common/base.html' %}

{% block content %}
    <form action=""method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <div>{{ form }}</div>
    <button type="submit">수정하기</button>
    </form>
{% endblock %}